baseURL = 'https://ramakrishna-psvs.github.io/'
languageCode = 'en-us'
title = 'RK'
enableEmoji = true
enableInlineShortcodes = true
theme = "paper"

disqusShortname = ''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # color style
  color = 'linen'

  # header social icons
  twitter = 'HypoLoco'
  github = 'ramakrishna-psvs'
  instagram = 'rama.krishna__'
  rss = true

  # home page profile
  avatar = 'heyofreak19@gmail.com'
  name = 'Rama Krishna Pinjala'
  bio = '17. Interests: F1, BioTech,Economcis, Transport and Travel Industry,International Affairs and Diplomacy, Coding'
   
  # misc
  giscusTheme="preferred_color_scheme" 
  disableComments=false



  [menu]
  
    [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 1
    [[menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 3
    [[menu.main]]
      identifier = "cv"
      name = "Resume"
      url = "https://www.notion.so/Extra-Curriculars-a5e8266567fa416bbbe9a603c46863c9?pvs=4"
      weight = 2

  [taxonomies]
    category = "topics"
    tag = "tags"
    series = "series"

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

custom_css = ["css/custom.css"]
[[redirects]]
  from = "/resume/"
  to = "https://www.notion.so/Extra-Curriculars-a5e8266567fa416bbbe9a603c46863c9?pvs=4"
  status = 302


