baseURL = 'https://ramakrishna-psvs.github.io/'
languageCode = 'en-us'
title = 'Rama Krishna'
enableEmoji = true

theme = "paper"

disqusShortname = ''

[params]
  # color style
  color = 'linen'

  # header social icons
  twitter = 'HypoLoco'
  github = 'ramakrishna-psvs'
  instagram = 'rama.krishna__'
  rss = true

  # home page profile
  avatar = 'heyofreak19@gmail.com'
  name = 'Rama Krishna Pinjala'
  bio = 'Hey! I like to write about F1, BioTech, Transport and Travel Industry,International Affairs and Diplomacy, Coding'

  # misc
  math = true

  [menu]
  
    [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 10
    [[menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 10

  [taxonomies]
    category = "topics"
    tag = "tags"
    series = "series"
