baseURL = 'https://ramakrishna-psvs.github.io/'
languageCode = 'en-us'
title = 'Rama Krishna'

theme = "paper"

disqusShortname = ''

[params]
  # color style
  color = 'linen'

  # header social icons
  twitter = 'HypoLoco'
  github = 'ramakrishna-psvs'
  instagram = 'rama.krishna__'
  rss = true

  # home page profile
  avatar = 'heyofreak19@gmail.com'
  name = 'Rama Krishna Pinjala'
  bio = 'Hi!'

  # misc
  math = true
