baseURL = 'https://ramakrishna-psvs.github.io/'
languageCode = 'en-us'
title = 'Rama Krishna'
enableEmoji = true
enableInlineShortcodes = true
theme = "paper"

disqusShortname = ''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # color style
  color = 'linen'

  # header social icons
  twitter = 'HypoLoco'
  github = 'ramakrishna-psvs'
  instagram = 'rama.krishna__'
  rss = true

  # home page profile
  avatar = 'heyofreak19@gmail.com'
  name = 'Rama Krishna Pinjala'
  bio = '16. I like F1, BioTech, Transport and Travel Industry,International Affairs and Diplomacy, Coding'
   
  # misc
  giscusTheme="preferred_color_scheme" 
  disableComments=false



  [menu]
  
    [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 10
    [[menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 10

  [taxonomies]
    category = "topics"
    tag = "tags"
    series = "series"

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

custom_css = ["css/custom.css"]


